### ISSUE TITLE
Misc. issues from my installation

### ISSUE THREAD

**Issue by kylepjohnson** [diyclassics/cltk_readers#11]
I have a PR coming with some small things. But here are a few bigger errors that I found.

``` python
>>> tess.describe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kylejohnson/cltk_readers/cltkreaders/readers.py", line 241, in describe
    for sent in self.sents(fileids):
  File "/Users/kylejohnson/cltk_readers/cltkreaders/readers.py", line 145, in sents
    for text in self.texts(fileids):
  File "/Users/kylejohnson/cltk_readers/cltkreaders/readers.py", line 131, in texts
    for doc_row in self.doc_rows(fileids):
  File "/Users/kylejohnson/cltk_readers/cltkreaders/readers.py", line 119, in doc_rows
    k, v = line.split('>', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Returns nothing:
``` python
>>> tess.check_corpus()
```

The filepath is wrong here. But where is this code defined? I couldn't find it.

``` python
>>> tess.citation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/corpus/reader/api.py", line 151, in citation
    with self.open(self._citation) as f:
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/corpus/reader/api.py", line 231, in open
    stream = self._root.join(file).open(encoding)
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/data.py", line 334, in join
    return FileSystemPathPointer(_path)
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/data.py", line 312, in __init__
    raise OSError("No such file or directory: %r" % _path)
OSError: No such file or directory: '/Users/kylejohnson/cltk_data/lat/text/lat_text_tesserae/texts/citation.bib'
```

``` python
>>> tess.license()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/corpus/reader/api.py", line 144, in license
    with self.open(self._license) as f:
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/corpus/reader/api.py", line 231, in open
    stream = self._root.join(file).open(encoding)
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/data.py", line 334, in join
    return FileSystemPathPointer(_path)
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/kylejohnson/.pyenv/versions/cltkReaders/lib/python3.9/site-packages/nltk/data.py", line 312, in __init__
    raise OSError("No such file or directory: %r" % _path)
OSError: No such file or directory: '/Users/kylejohnson/cltk_data/lat/text/lat_text_tesserae/texts/LICENSE'
```

**Comment by kylepjohnson** [comment]
Also, about the first install:

- Using 3.9.10, new virtual env
- Installation w/ `python setup.py install` failed due to no numpy
- Ran `pip install -r requirements.txt` and then `python setup.py install` worked
- W/o Tesserae Latin texts, the download worked. but the message is

**Comment by diyclassics** [comment]
> ```python
> ValueError: not enough values to unpack (expected 2, got 1)
> ```

This is a properly a problem with the corpus (and I will update and fix there)—that said, I can code defensively against this kind of inconsistency in the formatting.

**Comment by diyclassics** [comment]
> ```python
> tess.license()
> ```

Good catch... Found the issue—this corpus has the license in the parent folder of the corpus `root` (as `root` is defined by `CorpusReader`). Overriding that method and outputting the correct license location and filetype.

**Comment by diyclassics** [comment]
> * W/o Tesserae Latin texts, the download worked. but the message is

Looks like something dropped out here.
